-- =====================================================
-- LA TAVERNETTA - RAILWAY DATABASE IMPORT
-- =====================================================
-- Ovaj fajl sadrži svih 130 menu items iz Replit baze
-- Koristi ga za import u Railway PostgreSQL bazu
-- =====================================================

-- KORAK 1: Prvo obriši postojeće podatke (ako postoje)
DELETE FROM menu_items;

-- KORAK 2: Resetuj sequence za ID
ALTER SEQUENCE menu_items_id_seq RESTART WITH 1;

-- KORAK 3: Ubaci sve menu items
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Vegetariana', 'Paradajz sos, kačkavalj, tikvice, patlidžan, paprika, masline, origano', 'pizza', NULL, '[{"name": "32cm", "price": 950}, {"name": "42cm", "price": 1400}]', '/menu-images/vegetariana_pizza_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Margarita', 'Paradajz sos, mozzarella, bosiljak', 'pizza', NULL, '[{"name": "32cm", "price": 750}, {"name": "42cm", "price": 1150}]', '/menu-images/margarita_pizza.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Capricciosa', 'Paradajz sos, kačkavalj, šunka, pečurke', 'pizza', NULL, '[{"name": "32cm", "price": 900}, {"name": "42cm", "price": 1350}]', '/menu-images/capricciosa_pizza.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Vesuvio', 'Paradajz sos, kačkavalj, kulen, feferoni', 'pizza', NULL, '[{"name": "32cm", "price": 950}, {"name": "42cm", "price": 1400}]', '/menu-images/vesuvio_pizza.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Funghi', 'Paradajz sos, kačkavalj, pečurke, origano', 'pizza', NULL, '[{"name": "32cm", "price": 850}, {"name": "42cm", "price": 1300}]', '/menu-images/funghi_mushroom_pizza_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Tonno', 'Paradajz sos, kačkavalj, tunjevina, luk, masline', 'pizza', NULL, '[{"name": "32cm", "price": 950}, {"name": "42cm", "price": 1450}]', '/menu-images/tonno_tuna_pizza_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Diavola', 'Paradajz sos, kačkavalj, ljuta kobasica, feferoni', 'pizza', NULL, '[{"name": "32cm", "price": 950}, {"name": "42cm", "price": 1400}]', '/menu-images/diavola_pizza.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Parmegiana', 'Paradajz sos, kačkavalj, pršuta, parmezan, rukola', 'pizza', NULL, '[{"name": "32cm", "price": 1100}, {"name": "42cm", "price": 1600}]', '/menu-images/parmegiana_pizza.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Quattro Stagioni', 'Paradajz sos, kačkavalj, šunka, pečurke, artičoke, masline', 'pizza', NULL, '[{"name": "32cm", "price": 1000}, {"name": "42cm", "price": 1500}]', '/menu-images/quattro_stagioni_pizza.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Quattro Formaggi', 'Paradajz sos, mozzarella, gorgonzola, parmezan, kačkavalj', 'pizza', NULL, '[{"name": "32cm", "price": 1000}, {"name": "42cm", "price": 1500}]', '/menu-images/quattro_formaggi_pizza.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Paragina', 'Paradajz sos, kačkavalj, pileći file, kukuruz, paprika', 'pizza', NULL, '[{"name": "32cm", "price": 950}, {"name": "42cm", "price": 1400}]', '/menu-images/paragina_chicken_pizza_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Fuoco Nel Fuoco', 'Paradajz sos, kačkavalj, ljuta kobasica, feferoni, chili', 'pizza', NULL, '[{"name": "32cm", "price": 1000}, {"name": "42cm", "price": 1500}]', '/menu-images/fuoco_spicy_pizza_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Caesar Pizza', 'Beli sos, piletina, parmezan, zelena salata, cherry paradajz', 'pizza', NULL, '[{"name": "32cm", "price": 1050}, {"name": "42cm", "price": 1550}]', '/menu-images/caesar_pizza.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Bergamo', 'Krem sir, gorgonzola, pečurke, pršuta, parmezan', 'pizza', NULL, '[{"name": "32cm", "price": 1100}, {"name": "42cm", "price": 1650}]', '/menu-images/bergamo_pizza.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Pulled Pork', 'BBQ sos, pulled pork, crveni luk, kiseli krastavci', 'pizza', NULL, '[{"name": "32cm", "price": 1150}, {"name": "42cm", "price": 1700}]', '/menu-images/pulled_pork_bbq_pizza_white.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Siciliana', 'Paradajz sos, kačkavalj, kaperi, sardele, masline', 'pizza', NULL, '[{"name": "32cm", "price": 1000}, {"name": "42cm", "price": 1500}]', '/menu-images/siciliana_anchovy_pizza_white.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Calabrese', 'Paradajz sos, kačkavalj, nduja, feferoni, origano', 'pizza', NULL, '[{"name": "32cm", "price": 1050}, {"name": "42cm", "price": 1550}]', '/menu-images/calabrese_nduja_pizza_white.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Pot Pie Pizza', 'Bolognese sos, pečurke, kačkavalj, puter', 'pizza', NULL, '[{"name": "32cm", "price": 1100}, {"name": "42cm", "price": 1650}]', '/menu-images/pot-pie-pizza.png', true, false, true);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Pasta Bolognese', 'Špagete sa domaćim bolognese sosom', 'pasta', 850, NULL, '/menu-images/pasta_bolognese.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Pasta Carbonara', 'Špagete, slanina, jaje, parmezan, biber', 'pasta', 900, NULL, '/menu-images/pasta_carbonara_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Pasta Pesto', 'Špagete sa domaćim pesto sosom i parmezanom', 'pasta', 850, NULL, '/menu-images/pasta_pesto.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Pasta Quattro Formaggi', 'Špagete sa četiri vrste sira', 'pasta', 950, NULL, '/menu-images/pasta_quattro_formaggi_white.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Pasta Pomodoro', 'Špagete sa svežim paradajz sosom i bosiljkom', 'pasta', 750, NULL, '/menu-images/pasta_pomodoro_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Pasta Tuna', 'Špagete sa tunjevinom, kaperima i maslinovim uljem', 'pasta', 900, NULL, '/menu-images/pasta_tuna_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Pasta Funghi', 'Špagete sa pečurkama i kremastim sosom', 'pasta', 850, NULL, '/menu-images/pasta_funghi_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Pasta Vegetariana', 'Špagete sa grilovanih povrćem', 'pasta', 800, NULL, '/menu-images/pasta_vegetariana_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Caesar salata', 'Zelena salata, piletina, parmezan, krutoni, caesar dressing', 'salata', 850, NULL, '/menu-images/caesar_salata.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Grčka salata', 'Paradajz, krastavac, paprika, luk, masline, feta sir', 'salata', 700, NULL, '/menu-images/grcka_salata.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Tuna salata', 'Mešana zelena salata, tunjevina, jaje, paradajz, masline', 'salata', 800, NULL, '/menu-images/tuna_salata.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Caprese salata', 'Paradajz, mozzarella, bosiljak, maslinovo ulje', 'salata', 750, NULL, '/menu-images/caprese_salata.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Salata sa rukolom', 'Rukola, cherry paradajz, parmezan, balzamiko', 'salata', 700, NULL, '/menu-images/rukola_salata.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Letnja salata', 'Mešana zelena salata, krastavac, kukuruz, šargarepa', 'salata', 600, NULL, '/menu-images/letnja_salata_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Šopska salata', 'Paradajz, krastavac, paprika, luk, sir', 'salata', 550, NULL, '/menu-images/sopska_salata.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Caprese sendvič', 'Mozzarella, paradajz, bosiljak, pesto', 'sendvic', 650, NULL, '/menu-images/caprese_sandwich_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Srpski sendvič', 'Kajmak, pršuta, paprika, krastavac', 'sendvic', 700, NULL, '/menu-images/srpski_sendvic.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Italian Deli sendvič', 'Pršuta, salama, sir, paradajz, salata', 'sendvic', 750, NULL, '/menu-images/italian_deli_sendvic.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Caesar sendvič', 'Piletina, parmezan, salata, caesar dressing', 'sendvic', 700, NULL, '/menu-images/caesar_sendvic.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Domaći sendvič', 'Domaća kobasica, kajmak, ajvar', 'sendvic', 650, NULL, '/menu-images/domaci_serbian_sandwich_white.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Tuna sendvič', 'Tunjevina, salata, paradajz, majonez', 'sendvic', 700, NULL, '/menu-images/tuna_sandwich_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Quattro Formaggi sendvič', 'Četiri vrste sira, paradajz', 'sendvic', 700, NULL, '/menu-images/quattro_formaggi_sandwich_white.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Mesni sendvič', 'Slanina, šunka, sir, jaje, salata', 'sendvic', 750, NULL, '/menu-images/mesni_meat_sandwich_white.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Zlatiborski sendvič', 'Pršuta, kajmak, paprika', 'sendvic', 700, NULL, '/menu-images/zlatiborski_prosciutto_sandwich.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Panirani pileći štapići', 'Hrskavi pileći štapići sa sosom po izboru', 'glavno_jelo', 750, NULL, '/menu-images/panirani_pileci_stapici.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Bečka šnicla', 'Klasična bečka šnicla sa prilogom', 'glavno_jelo', 950, NULL, '/menu-images/becka_snicla.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Pohovani file sa gorgonzolom', 'Pileći file punjen gorgonzolom', 'glavno_jelo', 1050, NULL, '/menu-images/gorgonzola_stuffed_chicken_white.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Pohovani file sa parmezanom', 'Pileći file sa parmezanom i rukolom', 'glavno_jelo', 1050, NULL, '/menu-images/parmesan_chicken_arugula_white.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Lasagne', 'Domaće lasagne sa bolognese sosom', 'glavno_jelo', 900, NULL, '/menu-images/lasagne_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Marinirana krilca', 'Pikantna pileća krilca', 'glavno_jelo', 750, NULL, '/menu-images/marinated_chicken_wings_white.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Hladni tanjir', 'Izbor suhomesnatih proizvoda i sireva', 'glavno_jelo', 1200, NULL, '/menu-images/cold_meat_platter_white.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Ćevapi', 'Domaći ćevapi sa kajmakom i lepinjom', 'glavno_jelo', 800, NULL, '/menu-images/cevapi_serbian_dish_white.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Omlet', 'Klasičan omlet sa sirom', 'dorucak', 450, NULL, '/menu-images/omlet.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Omlet sa šunkom', 'Omlet sa šunkom i sirom', 'dorucak', 500, NULL, '/menu-images/ham_cheese_omelette_white.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Omlet sa povrćem', 'Omlet sa grilovanih povrćem', 'dorucak', 500, NULL, '/menu-images/vegetable_omelette_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Jaja i kobaja', 'Jaja na oko sa domaćom kobasicom', 'dorucak', 550, NULL, '/menu-images/eggs_sausage_breakfast_white.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Kranjska kobasica', 'Kranjska kobasica sa senfom', 'dorucak', 500, NULL, '/menu-images/kranjska_sausage_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Käsekrainer', 'Kobasica punjena sirom', 'dorucak', 550, NULL, '/menu-images/kasekrainer.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Calzone šunka', 'Presavijen sa šunkom i sirom', 'dorucak', 700, NULL, '/menu-images/calzone_ham_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Calzone capricciosa', 'Presavijen sa šunkom, pečurkama i sirom', 'dorucak', 750, NULL, '/menu-images/calzone_capricciosa_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Espresso', 'Klasičan espresso', 'topli_napici', 150, NULL, '/menu-images/espresso_coffee_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Espresso doppio', 'Dupli espresso', 'topli_napici', 200, NULL, '/menu-images/espresso_coffee_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Espresso macchiato', 'Espresso sa malo mleka', 'topli_napici', 180, NULL, '/menu-images/espresso_coffee_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Cappuccino', 'Espresso sa penjenim mlekom', 'topli_napici', 250, NULL, '/menu-images/cappuccino_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Caffè latte', 'Kafa sa puno mleka', 'topli_napici', 280, NULL, '/menu-images/caffe_latte_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Topla čokolada', 'Kremasta topla čokolada', 'topli_napici', 300, NULL, '/menu-images/hot_chocolate_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Bela topla čokolada', 'Kremasta bela topla čokolada', 'topli_napici', 300, NULL, '/menu-images/white_hot_chocolate_white.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Čaj', 'Razne vrste čaja', 'topli_napici', 200, NULL, '/menu-images/tea_cup_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Nes kafa', 'Instant kafa', 'topli_napici', 200, NULL, '/menu-images/espresso_coffee_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Shake vanila', 'Vanila šejk', 'topli_napici', 350, NULL, '/menu-images/vanilla_milkshake_white.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Shake čokolada', 'Čokoladni šejk', 'topli_napici', 350, NULL, '/menu-images/chocolate_milkshake_white.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Shake jagoda', 'Šejk od jagode', 'topli_napici', 350, NULL, '/menu-images/strawberry_milkshake_white.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Shake banana', 'Banana šejk', 'topli_napici', 350, NULL, '/menu-images/banana_milkshake_white.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Kisela voda', '0.25l', 'bezalkoholno', 120, NULL, '/menu-images/sparkling_water_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Negazirana voda', '0.25l', 'bezalkoholno', 120, NULL, '/menu-images/still_water_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Kisela voda 0.75l', '0.75l', 'bezalkoholno', 200, NULL, '/menu-images/sparkling_water_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Negazirana voda 0.75l', '0.75l', 'bezalkoholno', 200, NULL, '/menu-images/still_water_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Coca-Cola', '0.25l', 'bezalkoholno', 200, NULL, '/menu-images/cola_glass_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Coca-Cola Zero', '0.25l', 'bezalkoholno', 200, NULL, '/menu-images/cola_glass_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Fanta', '0.25l', 'bezalkoholno', 200, NULL, '/menu-images/cola_glass_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Sprite', '0.25l', 'bezalkoholno', 200, NULL, '/menu-images/cola_glass_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Schweppes Tonic', '0.25l', 'bezalkoholno', 200, NULL, '/menu-images/tonic_water_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Schweppes Bitter Lemon', '0.25l', 'bezalkoholno', 200, NULL, '/menu-images/tonic_water_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Sok od jabuke', '0.25l', 'bezalkoholno', 200, NULL, '/menu-images/apple_juice_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Sok od pomorandže', '0.25l', 'bezalkoholno', 200, NULL, '/menu-images/orange_juice_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Sok od breskve', '0.25l', 'bezalkoholno', 200, NULL, '/menu-images/orange_juice_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Sok od višnje', '0.25l', 'bezalkoholno', 200, NULL, '/menu-images/cherry_juice_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Sok od jagode', '0.25l', 'bezalkoholno', 200, NULL, '/menu-images/cherry_juice_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Ceđena pomorandža', 'Sveže ceđena pomorandža', 'bezalkoholno', 350, NULL, '/menu-images/orange_juice_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Ceđena limunada', 'Sveže ceđena limunada', 'bezalkoholno', 300, NULL, '/menu-images/lemonade_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Red Bull', '0.25l', 'bezalkoholno', 350, NULL, '/menu-images/energy_drink_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Ledeni čaj breskva', '0.25l', 'bezalkoholno', 200, NULL, '/menu-images/peach_iced_tea_white.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Ledeni čaj limun', '0.25l', 'bezalkoholno', 200, NULL, '/menu-images/peach_iced_tea_white.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Šljivovica', '0.03l', 'alkohol', 200, NULL, '/menu-images/rakija_brandy_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Viljamovka', '0.03l', 'alkohol', 200, NULL, '/menu-images/rakija_brandy_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Loza', '0.03l', 'alkohol', 200, NULL, '/menu-images/rakija_brandy_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Kajsijevača', '0.03l', 'alkohol', 200, NULL, '/menu-images/rakija_brandy_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Dunjevača', '0.03l', 'alkohol', 200, NULL, '/menu-images/rakija_brandy_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Medovača', '0.03l', 'alkohol', 200, NULL, '/menu-images/rakija_brandy_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Johnnie Walker Red', '0.03l', 'alkohol', 300, NULL, '/menu-images/whiskey_glass_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Johnnie Walker Black', '0.03l', 'alkohol', 400, NULL, '/menu-images/whiskey_glass_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Jack Daniels', '0.03l', 'alkohol', 350, NULL, '/menu-images/whiskey_glass_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Jameson', '0.03l', 'alkohol', 350, NULL, '/menu-images/whiskey_glass_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Chivas Regal', '0.03l', 'alkohol', 450, NULL, '/menu-images/whiskey_glass_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Absolut Vodka', '0.03l', 'alkohol', 250, NULL, '/menu-images/vodka_shot_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Smirnoff', '0.03l', 'alkohol', 250, NULL, '/menu-images/vodka_shot_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Grey Goose', '0.03l', 'alkohol', 400, NULL, '/menu-images/vodka_shot_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Havana Club', '0.03l', 'alkohol', 300, NULL, '/menu-images/rum_shot_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Bacardi', '0.03l', 'alkohol', 300, NULL, '/menu-images/rum_shot_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Jagermeister', '0.03l', 'alkohol', 300, NULL, '/menu-images/jagermeister_shot_white.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Baileys', '0.03l', 'alkohol', 300, NULL, '/menu-images/baileys_cream_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Aperol', '0.03l', 'alkohol', 300, NULL, '/menu-images/aperol_spritz_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Campari', '0.03l', 'alkohol', 300, NULL, '/menu-images/campari_aperitif_white.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Gin Beefeater', '0.03l', 'alkohol', 300, NULL, '/menu-images/gin_tonic_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Gin Hendricks', '0.03l', 'alkohol', 450, NULL, '/menu-images/gin_tonic_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Točeno pivo 0.3l', 'Točeno pivo', 'alkohol', 250, NULL, '/menu-images/draft_beer_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Točeno pivo 0.5l', 'Točeno pivo', 'alkohol', 350, NULL, '/menu-images/draft_beer_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Heineken', '0.33l flaša', 'alkohol', 300, NULL, '/menu-images/beer_bottle_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Stella Artois', '0.33l flaša', 'alkohol', 300, NULL, '/menu-images/beer_bottle_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Corona', '0.33l flaša', 'alkohol', 350, NULL, '/menu-images/beer_bottle_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Budweiser', '0.33l flaša', 'alkohol', 300, NULL, '/menu-images/beer_bottle_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Zaječarsko', '0.5l flaša', 'alkohol', 250, NULL, '/menu-images/beer_bottle_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Lav', '0.5l flaša', 'alkohol', 250, NULL, '/menu-images/beer_bottle_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Jelen', '0.5l flaša', 'alkohol', 250, NULL, '/menu-images/beer_bottle_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Belo vino čaša', 'Čaša belog vina', 'alkohol', 250, NULL, '/menu-images/white_wine_glass_white.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Crno vino čaša', 'Čaša crnog vina', 'alkohol', 250, NULL, '/menu-images/red_wine_glass_white.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Rose vino čaša', 'Čaša rose vina', 'alkohol', 250, NULL, '/menu-images/rose_wine_glass_white.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Belo vino flaša', 'Flaša belog vina', 'alkohol', 1200, NULL, '/menu-images/wine_bottle_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Crno vino flaša', 'Flaša crnog vina', 'alkohol', 1200, NULL, '/menu-images/wine_bottle_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Rose vino flaša', 'Flaša rose vina', 'alkohol', 1200, NULL, '/menu-images/wine_bottle_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Aperol Spritz', 'Aperol, prosecco, soda', 'alkohol', 500, NULL, '/menu-images/aperol_spritz_white_background.png', true, false, false);
INSERT INTO menu_items (name, description, category, price, sizes, image_url, available, featured, is_new) VALUES ('Mojito', 'Rum, limeta, menta, soda', 'alkohol', 550, NULL, '/menu-images/mojito_cocktail_white_background.png', true, false, false);

-- =====================================================
-- KRAJ IMPORTA - Ukupno 130 menu items
-- =====================================================
